### PR TITLE
enhance(badge): adds go report badge

### PR DESCRIPTION
**Pull request by ashishranjan738**
Signed-off-by: ashishranjan738 <ashishranjan738@gmail.com>

### CODE REVIEW

**Comment by ashishranjan738** [comment]
@umamukkara, please review this.

**Comment by umamukkara** [comment]
@ashishranjan738 , can you make the go report badge appear next to travis-build. It is currently appearing one below the other

**Comment by ashishranjan738** [comment]
> @ashishranjan738 , can you make the go report badge appear next to travis-build. It is currently appearing one below the other

@umamukkara done in this PR https://github.com/kubemove/kubemove/pull/12

**Pull request merged**
